//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        public int IdAvatar { get; set; }
        public string AvatarName { get; set; }
        public byte[] imageAvatar { get; set; }
    }
}
