//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestJeopardyServidor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BdActions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BdActions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestJeopardyServidor.Properties.BdActions", typeof(BdActions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from  [dbo].[Friends] where [Player_IdPlayer] = 53 AND [PlayerFriend_IdPlayer] = 54
        ///GO.
        /// </summary>
        public static string DeleteFrienship5354 {
            get {
                return ResourceManager.GetString("DeleteFrienship5354", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [Jeopardy].[dbo].[GamePlayers] WHERE PlaceInGame = 10;.
        /// </summary>
        public static string DeleteGamePlayers {
            get {
                return ResourceManager.GetString("DeleteGamePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [Jeopardy].[dbo].[Games] WHERE RoomCode = 00000;.
        /// </summary>
        public static string DeleteGames00000 {
            get {
                return ResourceManager.GetString("DeleteGames00000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [Jeopardy].[dbo].[Games] WHERE RoomCode = 22222;.
        /// </summary>
        public static string DeleteGames22222 {
            get {
                return ResourceManager.GetString("DeleteGames22222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [Jeopardy].[dbo].[Players] WHERE State_idState &gt;= 3;.
        /// </summary>
        public static string DeletePlayers {
            get {
                return ResourceManager.GetString("DeletePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [Jeopardy].[dbo].[States] WHERE IdState &gt; 3;.
        /// </summary>
        public static string DeleteStates {
            get {
                return ResourceManager.GetString("DeleteStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [Jeopardy].[dbo].[Users] WHERE name = &apos;&apos;;.
        /// </summary>
        public static string DeleteUsers {
            get {
                return ResourceManager.GetString("DeleteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Players]
        ///   SET [GeneralPoints] = 0
        ///      ,[NoReports] = 0
        ///      ,[State_idState] = 1
        ///      ,[IdAvatarActual] = 7
        /// WHERE IdPlayer = 25;.
        /// </summary>
        public static string RestorePlayer25 {
            get {
                return ResourceManager.GetString("RestorePlayer25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Users]
        ///   SET 
        ///      [TwitterUserName] = &apos;&apos;
        /// WHERE IdUser = 22.
        /// </summary>
        public static string RestoreTwitter {
            get {
                return ResourceManager.GetString("RestoreTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Users]
        ///   SET [EmailAddress] = &apos;tristan@gmail.com&apos;
        ///      ,[Password] = &apos;614bac48e79de791a7222dd0a68efce7ec078e19f8669d0899c9838949a68f96&apos;
        ///      ,[Name] = &apos;tris&apos;
        /// WHERE IdUser = 22;.
        /// </summary>
        public static string RestoreUser22 {
            get {
                return ResourceManager.GetString("RestoreUser22", resourceCulture);
            }
        }
    }
}
