//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvatarPlayer
    {
        public int IdAvatarPlayer { get; set; }
        public int Avatar_IdAvatar { get; set; }
        public int Player_IdPlayer { get; set; }
    
        public virtual Avatar Avatar { get; set; }
        public virtual Player Player { get; set; }
    }
}
