//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Awnser
    {
        public int IdAwnser { get; set; }
        public string SpanishAwnserDescription { get; set; }
        public string EnglichAwnserDescription { get; set; }
        public int CategoryIdCategory { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
