//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baneo
    {
        public int IdBaneo { get; set; }
        public Nullable<System.DateTime> BanTimeBegin { get; set; }
        public Nullable<System.DateTime> BanTimeFinish { get; set; }
        public int Player_IdPlayer { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
