//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public int idBoard { get; set; }
        public string Game_RoomCode { get; set; }
        public int Category_IdCategory { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Game Game { get; set; }
    }
}
