//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeopardyGame.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blizzard.
        /// </summary>
        public static string Blizzard {
            get {
                return ResourceManager.GetString("Blizzard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celestial.
        /// </summary>
        public static string Celestial {
            get {
                return ResourceManager.GetString("Celestial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CyberNinja.
        /// </summary>
        public static string CyberNinja {
            get {
                return ResourceManager.GetString("CyberNinja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental.
        /// </summary>
        public static string Elemental {
            get {
                return ResourceManager.GetString("Elemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EternalRogue.
        /// </summary>
        public static string EternalRogue {
            get {
                return ResourceManager.GetString("EternalRogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GalaxyEx.
        /// </summary>
        public static string GalaxyEx {
            get {
                return ResourceManager.GetString("GalaxyEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guest@email.
        /// </summary>
        public static string GuestMail {
            get {
                return ResourceManager.GetString("GuestMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GuestName {
            get {
                return ResourceManager.GetString("GuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456789.
        /// </summary>
        public static string GuestPassword {
            get {
                return ResourceManager.GetString("GuestPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfernoWar.
        /// </summary>
        public static string InfernoWar {
            get {
                return ResourceManager.GetString("InfernoWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jeopardy.tec@Gmail.com.
        /// </summary>
        public static string JeopardyEmail {
            get {
                return ResourceManager.GetString("JeopardyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lqen ymkw itqt rrmn.
        /// </summary>
        public static string JeopardyPassword {
            get {
                return ResourceManager.GetString("JeopardyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just.
        /// </summary>
        public static string Just {
            get {
                return ResourceManager.GetString("Just", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JustMaster.
        /// </summary>
        public static string JustMaster {
            get {
                return ResourceManager.GetString("JustMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JustNoob.
        /// </summary>
        public static string JustNoob {
            get {
                return ResourceManager.GetString("JustNoob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LunarAssassin.
        /// </summary>
        public static string LunarAssassin {
            get {
                return ResourceManager.GetString("LunarAssassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MidnightVoy.
        /// </summary>
        public static string MidnightVoy {
            get {
                return ResourceManager.GetString("MidnightVoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MysticSeeker.
        /// </summary>
        public static string MysticSeeker {
            get {
                return ResourceManager.GetString("MysticSeeker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NebulaStriker.
        /// </summary>
        public static string NebulaStriker {
            get {
                return ResourceManager.GetString("NebulaStriker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoBody.
        /// </summary>
        public static string NoBody {
            get {
                return ResourceManager.GetString("NoBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoobMaster.
        /// </summary>
        public static string NoobMaster {
            get {
                return ResourceManager.GetString("NoobMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NovaVortex.
        /// </summary>
        public static string NovaVortex {
            get {
                return ResourceManager.GetString("NovaVortex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papikra.
        /// </summary>
        public static string Papikra {
            get {
                return ResourceManager.GetString("Papikra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoenixKnight.
        /// </summary>
        public static string PhoenixKnight {
            get {
                return ResourceManager.GetString("PhoenixKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantum.
        /// </summary>
        public static string Quantum {
            get {
                return ResourceManager.GetString("Quantum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantumGamer.
        /// </summary>
        public static string QuantumGamer {
            get {
                return ResourceManager.GetString("QuantumGamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShadowRunner.
        /// </summary>
        public static string ShadowRunner {
            get {
                return ResourceManager.GetString("ShadowRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.Gmail.com.
        /// </summary>
        public static string smptGmail {
            get {
                return ResourceManager.GetString("smptGmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolarSorcerer.
        /// </summary>
        public static string SolarSorcerer {
            get {
                return ResourceManager.GetString("SolarSorcerer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starlight.
        /// </summary>
        public static string Starlight {
            get {
                return ResourceManager.GetString("Starlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThunderSpec.
        /// </summary>
        public static string ThunderSpec {
            get {
                return ResourceManager.GetString("ThunderSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TigerWoods.
        /// </summary>
        public static string TigerWoods {
            get {
                return ResourceManager.GetString("TigerWoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachiturro.
        /// </summary>
        public static string Wachiturro {
            get {
                return ResourceManager.GetString("Wachiturro", resourceCulture);
            }
        }
    }
}
