//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Data.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.GeneralPoints = 0;
        }
    
        public int IdPlayer { get; set; }
        public Nullable<long> GeneralPoints { get; set; }
        public long NoReports { get; set; }
        public int State_idState { get; set; }
        public Nullable<int> IdAvatarActual { get; set; }
    
        public virtual State State { get; set; }
        public virtual User User { get; set; }
    }
}
