//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionsPaths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsPaths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeopardyGame.Properties.ExceptionsPaths", typeof(ExceptionsPaths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialNumber.
        /// </summary>
        internal static string CharacteristicToConsider {
            get {
                return ResourceManager.GetString("CharacteristicToConsider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyyMMdd_HHmmss.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logFile_{0}.txt.
        /// </summary>
        internal static string logFileName {
            get {
                return ResourceManager.GetString("logFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Users\\dnava\\source\\repos\\JeopardyProject\\JeopardyGameTecnologias\\JeopardyProject\\JeopardyGameClient\\Logs\\.
        /// </summary>
        internal static string PathDodonaji {
            get {
                return ResourceManager.GetString("PathDodonaji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\Users\\wachi\\OneDrive\\Documentos\\GitHub\\JeopardyTecnologias\\JeopardyGameClient\\Exceptions\\Logs.
        /// </summary>
        internal static string PathTris {
            get {
                return ResourceManager.GetString("PathTris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Win32_DiskDrive.
        /// </summary>
        internal static string SelectPC {
            get {
                return ResourceManager.GetString("SelectPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6479_A753_1090_3048..
        /// </summary>
        internal static string TrisPCId {
            get {
                return ResourceManager.GetString("TrisPCId", resourceCulture);
            }
        }
    }
}
