//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeopardyGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string btnEnter {
            get {
                return ResourceManager.GetString("btnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sing in.
        /// </summary>
        public static string btnRegistrer {
            get {
                return ResourceManager.GetString("btnRegistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acept.
        /// </summary>
        public static string bttAccept {
            get {
                return ResourceManager.GetString("bttAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancell.
        /// </summary>
        public static string bttCancellAction {
            get {
                return ResourceManager.GetString("bttCancellAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string bttContinue {
            get {
                return ResourceManager.GetString("bttContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter game.
        /// </summary>
        public static string bttEnterGame {
            get {
                return ResourceManager.GetString("bttEnterGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string bttFriends {
            get {
                return ResourceManager.GetString("bttFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New game.
        /// </summary>
        public static string bttNewGame {
            get {
                return ResourceManager.GetString("bttNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string bttSaveUser {
            get {
                return ResourceManager.GetString("bttSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is the code for your verifification in Jeopardy, enter it in the code field to start the fun..
        /// </summary>
        public static string EmailCodeDescrip {
            get {
                return ResourceManager.GetString("EmailCodeDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        public static string EmailSubjectCode {
            get {
                return ResourceManager.GetString("EmailSubjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string lblCodeDescrip {
            get {
                return ResourceManager.GetString("lblCodeDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string lblEmailDescripCreateAcc {
            get {
                return ResourceManager.GetString("lblEmailDescripCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty field.
        /// </summary>
        public static string lblEmptyField {
            get {
                return ResourceManager.GetString("lblEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fail to register.
        /// </summary>
        public static string lblFailToRegisterUser {
            get {
                return ResourceManager.GetString("lblFailToRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a invalid email.
        /// </summary>
        public static string lblInvalidEmail {
            get {
                return ResourceManager.GetString("lblInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string lblNameDescripCreateAcc {
            get {
                return ResourceManager.GetString("lblNameDescripCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capital rules.
        /// </summary>
        public static string lblPassCapitalRuleDesc {
            get {
                return ResourceManager.GetString("lblPassCapitalRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not equal to email.
        /// </summary>
        public static string lblPassEqualsEmailRuleDesc {
            get {
                return ResourceManager.GetString("lblPassEqualsEmailRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        public static string lblPassLengthRuleDesc {
            get {
                return ResourceManager.GetString("lblPassLengthRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Beetwen 10-30.
        /// </summary>
        public static string lblPassNumberRuleDesc {
            get {
                return ResourceManager.GetString("lblPassNumberRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put a puntuation mark.
        /// </summary>
        public static string lblPassPuntSigRuleDesc {
            get {
                return ResourceManager.GetString("lblPassPuntSigRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special chaacter.
        /// </summary>
        public static string lblPassSpeCharRuleDesc {
            get {
                return ResourceManager.GetString("lblPassSpeCharRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lblPasswordDescripCreateAcc {
            get {
                return ResourceManager.GetString("lblPasswordDescripCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lblPasswordLogIn {
            get {
                return ResourceManager.GetString("lblPasswordLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPasswordWrong {
            get {
                return ResourceManager.GetString("lblPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string lblRepeatedEmail {
            get {
                return ResourceManager.GetString("lblRepeatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RepeatedUsername.
        /// </summary>
        public static string lblRepeatedUserName {
            get {
                return ResourceManager.GetString("lblRepeatedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resent Code.
        /// </summary>
        public static string lblResentCode {
            get {
                return ResourceManager.GetString("lblResentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a username.
        /// </summary>
        public static string lblUserNameDescripCreateAcc {
            get {
                return ResourceManager.GetString("lblUserNameDescripCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User name.
        /// </summary>
        public static string lblUserNameLogIn {
            get {
                return ResourceManager.GetString("lblUserNameLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string LblWrongUserName {
            get {
                return ResourceManager.GetString("LblWrongUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A problem has ocurred.
        /// </summary>
        public static string SentEmailIssue {
            get {
                return ResourceManager.GetString("SentEmailIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A code was sent ....
        /// </summary>
        public static string txbCodeInstructions {
            get {
                return ResourceManager.GetString("txbCodeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A problem has ocurred while saving the user, try again..
        /// </summary>
        public static string txbErrorMessageRegisterUser {
            get {
                return ResourceManager.GetString("txbErrorMessageRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR.
        /// </summary>
        public static string txbErrorTitle {
            get {
                return ResourceManager.GetString("txbErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user has been saved succesfully.
        /// </summary>
        public static string txbInfoMessgSuccRegUser {
            get {
                return ResourceManager.GetString("txbInfoMessgSuccRegUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFORMATION.
        /// </summary>
        public static string txbUserRegisteredSuccTittle {
            get {
                return ResourceManager.GetString("txbUserRegisteredSuccTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are your sure, do want to cancell the process?.
        /// </summary>
        public static string txbWarningMessCloseWin {
            get {
                return ResourceManager.GetString("txbWarningMessCloseWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WARNING.
        /// </summary>
        public static string txbWarningTitle {
            get {
                return ResourceManager.GetString("txbWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code is wrong.
        /// </summary>
        public static string WrongCode {
            get {
                return ResourceManager.GetString("WrongCode", resourceCulture);
            }
        }
    }
}
