//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeopardyGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeopardyGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        public static string _2PlayerByTeam {
            get {
                return ResourceManager.GetString("2PlayerByTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose an image.
        /// </summary>
        public static string btnChoseImage {
            get {
                return ResourceManager.GetString("btnChoseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string btnEnter {
            get {
                return ResourceManager.GetString("btnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string btnEnterCode {
            get {
                return ResourceManager.GetString("btnEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string btnInvite {
            get {
                return ResourceManager.GetString("btnInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string btnLogIn {
            get {
                return ResourceManager.GetString("btnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sing in.
        /// </summary>
        public static string btnRegistrer {
            get {
                return ResourceManager.GetString("btnRegistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string btnSaveChanges {
            get {
                return ResourceManager.GetString("btnSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acept.
        /// </summary>
        public static string bttAccept {
            get {
                return ResourceManager.GetString("bttAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept Request.
        /// </summary>
        public static string bttAcceptFriendRequest {
            get {
                return ResourceManager.GetString("bttAcceptFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add .
        /// </summary>
        public static string bttAddFriend {
            get {
                return ResourceManager.GetString("bttAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string bttCancelGame {
            get {
                return ResourceManager.GetString("bttCancelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string bttCancellAction {
            get {
                return ResourceManager.GetString("bttCancellAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string bttContinue {
            get {
                return ResourceManager.GetString("bttContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline Request.
        /// </summary>
        public static string bttDeclineFriendRequest {
            get {
                return ResourceManager.GetString("bttDeclineFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminate.
        /// </summary>
        public static string bttEliminate {
            get {
                return ResourceManager.GetString("bttEliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter game.
        /// </summary>
        public static string bttEnterGame {
            get {
                return ResourceManager.GetString("bttEnterGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string bttFriends {
            get {
                return ResourceManager.GetString("bttFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string bttGuest {
            get {
                return ResourceManager.GetString("bttGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string bttInvite {
            get {
                return ResourceManager.GetString("bttInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New game.
        /// </summary>
        public static string bttNewGame {
            get {
                return ResourceManager.GetString("bttNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string bttPlayer {
            get {
                return ResourceManager.GetString("bttPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report.
        /// </summary>
        public static string bttReport {
            get {
                return ResourceManager.GetString("bttReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string bttSaveUser {
            get {
                return ResourceManager.GetString("bttSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string bttSearch {
            get {
                return ResourceManager.GetString("bttSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start game.
        /// </summary>
        public static string bttStartGame {
            get {
                return ResourceManager.GetString("bttStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is the code for your verifification in Jeopardy, enter it in the code field to start the fun..
        /// </summary>
        public static string EmailCodeDescrip {
            get {
                return ResourceManager.GetString("EmailCodeDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        public static string EmailSubjectCode {
            get {
                return ResourceManager.GetString("EmailSubjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error joining.
        /// </summary>
        public static string ErrorJoiningLobby {
            get {
                return ResourceManager.GetString("ErrorJoiningLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a game cancelled.
        /// </summary>
        public static string GameCancelled {
            get {
                return ResourceManager.GetString("GameCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game finished.
        /// </summary>
        public static string GameFinished {
            get {
                return ResourceManager.GetString("GameFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem sending the email.
        /// </summary>
        public static string GenericEmailIssue {
            get {
                return ResourceManager.GetString("GenericEmailIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories.
        /// </summary>
        public static string HostCategoriesPresentation {
            get {
                return ResourceManager.GetString("HostCategoriesPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a round 2.
        /// </summary>
        public static string HostRoun2Presentation {
            get {
                return ResourceManager.GetString("HostRoun2Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a re.
        /// </summary>
        public static string HostRound1Presentation {
            get {
                return ResourceManager.GetString("HostRound1Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last round.
        /// </summary>
        public static string HostRound3Presentation {
            get {
                return ResourceManager.GetString("HostRound3Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a invalid.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación enviada.
        /// </summary>
        public static string Invitation_sent {
            get {
                return ResourceManager.GetString("Invitation sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kicked.
        /// </summary>
        public static string KickedFromLobby {
            get {
                return ResourceManager.GetString("KickedFromLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a U sure.
        /// </summary>
        public static string lblBanConfirmationMessage {
            get {
                return ResourceManager.GetString("lblBanConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bane User.
        /// </summary>
        public static string lblBaneUserTitle {
            get {
                return ResourceManager.GetString("lblBaneUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string lblCodeDescrip {
            get {
                return ResourceManager.GetString("lblCodeDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game code.
        /// </summary>
        public static string lblCodeGame {
            get {
                return ResourceManager.GetString("lblCodeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room code.
        /// </summary>
        public static string lblCodeRoom {
            get {
                return ResourceManager.GetString("lblCodeRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string lblEditUserInformation {
            get {
                return ResourceManager.GetString("lblEditUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, you have been removed from the game lobby.
        /// </summary>
        public static string lblEliminateFromLobby {
            get {
                return ResourceManager.GetString("lblEliminateFromLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string lblEmailDescripCreateAcc {
            get {
                return ResourceManager.GetString("lblEmailDescripCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string lblEmailInformation {
            get {
                return ResourceManager.GetString("lblEmailInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty field.
        /// </summary>
        public static string lblEmptyField {
            get {
                return ResourceManager.GetString("lblEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string lblEnglishEU {
            get {
                return ResourceManager.GetString("lblEnglishEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error entering lobby, try again later.
        /// </summary>
        public static string lblErrorEnter {
            get {
                return ResourceManager.GetString("lblErrorEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fail to register.
        /// </summary>
        public static string lblFailToRegisterUser {
            get {
                return ResourceManager.GetString("lblFailToRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, the game has been canceled.
        /// </summary>
        public static string lblGameCancel {
            get {
                return ResourceManager.GetString("lblGameCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string lblGameLanguaje {
            get {
                return ResourceManager.GetString("lblGameLanguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid credentials, please try again.
        /// </summary>
        public static string lblinvalidCredentials {
            get {
                return ResourceManager.GetString("lblinvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a invalid email.
        /// </summary>
        public static string lblInvalidEmail {
            get {
                return ResourceManager.GetString("lblInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends list.
        /// </summary>
        public static string lblListOfFriends {
            get {
                return ResourceManager.GetString("lblListOfFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a chat.
        /// </summary>
        public static string lblLiveChat {
            get {
                return ResourceManager.GetString("lblLiveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, you are already logged in with these credentials..
        /// </summary>
        public static string lblLogInExist {
            get {
                return ResourceManager.GetString("lblLogInExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game mode:.
        /// </summary>
        public static string lblModalityGame {
            get {
                return ResourceManager.GetString("lblModalityGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More People.
        /// </summary>
        public static string lblMorePeopleFriendManager {
            get {
                return ResourceManager.GetString("lblMorePeopleFriendManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Friends.
        /// </summary>
        public static string lblMyFriendsFriendManager {
            get {
                return ResourceManager.GetString("lblMyFriendsFriendManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string lblNameDescripCreateAcc {
            get {
                return ResourceManager.GetString("lblNameDescripCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string lblNameInformation {
            get {
                return ResourceManager.GetString("lblNameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we were unable to generate a match, please leave the lobby and try again later.
        /// </summary>
        public static string lblNotGame {
            get {
                return ResourceManager.GetString("lblNotGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, there should only be two players per team.
        /// </summary>
        public static string lblNotTwoPlayers {
            get {
                return ResourceManager.GetString("lblNotTwoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There must be 4 players to access this option.
        /// </summary>
        public static string lblNumberOfPlayers {
            get {
                return ResourceManager.GetString("lblNumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a valid code.
        /// </summary>
        public static string lblnvalidCode {
            get {
                return ResourceManager.GetString("lblnvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capital rules.
        /// </summary>
        public static string lblPassCapitalRuleDesc {
            get {
                return ResourceManager.GetString("lblPassCapitalRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not equal to email.
        /// </summary>
        public static string lblPassEqualsEmailRuleDesc {
            get {
                return ResourceManager.GetString("lblPassEqualsEmailRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        public static string lblPassLengthRuleDesc {
            get {
                return ResourceManager.GetString("lblPassLengthRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Beetwen 10-30.
        /// </summary>
        public static string lblPassNumberRuleDesc {
            get {
                return ResourceManager.GetString("lblPassNumberRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put a puntuation mark.
        /// </summary>
        public static string lblPassPuntSigRuleDesc {
            get {
                return ResourceManager.GetString("lblPassPuntSigRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Special chaacter.
        /// </summary>
        public static string lblPassSpeCharRuleDesc {
            get {
                return ResourceManager.GetString("lblPassSpeCharRuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lblPasswordDescripCreateAcc {
            get {
                return ResourceManager.GetString("lblPasswordDescripCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lblPasswordLogIn {
            get {
                return ResourceManager.GetString("lblPasswordLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a password.
        /// </summary>
        public static string lblPasswordWrong {
            get {
                return ResourceManager.GetString("lblPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players in game:.
        /// </summary>
        public static string lblPlayersInGame {
            get {
                return ResourceManager.GetString("lblPlayersInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string lblProfileInformation {
            get {
                return ResourceManager.GetString("lblProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string lblRepeatedEmail {
            get {
                return ResourceManager.GetString("lblRepeatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RepeatedUsername.
        /// </summary>
        public static string lblRepeatedUserName {
            get {
                return ResourceManager.GetString("lblRepeatedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitude.
        /// </summary>
        public static string lblRequestFriendManager {
            get {
                return ResourceManager.GetString("lblRequestFriendManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resent Code.
        /// </summary>
        public static string lblResentCode {
            get {
                return ResourceManager.GetString("lblResentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sec.
        /// </summary>
        public static string lblSecondsAbrevation {
            get {
                return ResourceManager.GetString("lblSecondsAbrevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string lblSettingsIcon {
            get {
                return ResourceManager.GetString("lblSettingsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string lblSpanish {
            get {
                return ResourceManager.GetString("lblSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spanish.
        /// </summary>
        public static string lblSpanishMexico {
            get {
                return ResourceManager.GetString("lblSpanishMexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, the action has timed out, please try again later..
        /// </summary>
        public static string lblTimeExpired {
            get {
                return ResourceManager.GetString("lblTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User changes have been saved.
        /// </summary>
        public static string lblUpdateInformation {
            get {
                return ResourceManager.GetString("lblUpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, you already have more than three reports so you will have to create a new account to continue playing..
        /// </summary>
        public static string lblUserBanner {
            get {
                return ResourceManager.GetString("lblUserBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string lblUserNameDescripCreateAcc {
            get {
                return ResourceManager.GetString("lblUserNameDescripCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User name.
        /// </summary>
        public static string lblUserNameInformation {
            get {
                return ResourceManager.GetString("lblUserNameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User name.
        /// </summary>
        public static string lblUserNameLogIn {
            get {
                return ResourceManager.GetString("lblUserNameLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best players.
        /// </summary>
        public static string lblWinnerList {
            get {
                return ResourceManager.GetString("lblWinnerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, it was not possible to establish communication with the server at the moment, please try again later.
        /// </summary>
        public static string lblWithoutConection {
            get {
                return ResourceManager.GetString("lblWithoutConection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we couldn&apos;t recover your friends list at the moment, try again later..
        /// </summary>
        public static string lblWithoutFriends {
            get {
                return ResourceManager.GetString("lblWithoutFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong code.
        /// </summary>
        public static string lblWrongRoomCode {
            get {
                return ResourceManager.GetString("lblWrongRoomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not update user information.
        /// </summary>
        public static string lblWrongUpdateInformation {
            get {
                return ResourceManager.GetString("lblWrongUpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a username.
        /// </summary>
        public static string LblWrongUserName {
            get {
                return ResourceManager.GetString("LblWrongUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yuor Turn.
        /// </summary>
        public static string lblYourTurn {
            get {
                return ResourceManager.GetString("lblYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are u sure.
        /// </summary>
        public static string LeaveGameConfirmation {
            get {
                return ResourceManager.GetString("LeaveGameConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The LObby is full.
        /// </summary>
        public static string LobbyIsFull {
            get {
                return ResourceManager.GetString("LobbyIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The lobbbyDoes not exist.
        /// </summary>
        public static string LobbyNotExist {
            get {
                return ResourceManager.GetString("LobbyNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entity Exception.
        /// </summary>
        public static string MessageEntityException {
            get {
                return ResourceManager.GetString("MessageEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a had declined your friend request..
        /// </summary>
        public static string MessageFriRequeDeclined {
            get {
                return ResourceManager.GetString("MessageFriRequeDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Careful, You&apos;ve been reported, Now you have :.
        /// </summary>
        public static string MessageReported {
            get {
                return ResourceManager.GetString("MessageReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SQL EXCEPTION.
        /// </summary>
        public static string MessageSQLException {
            get {
                return ResourceManager.GetString("MessageSQLException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string MoreThan1Player {
            get {
                return ResourceManager.GetString("MoreThan1Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        public static string MustBe4Players {
            get {
                return ResourceManager.GetString("MustBe4Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Individual.
        /// </summary>
        public static string rdbIndividual {
            get {
                return ResourceManager.GetString("rdbIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team.
        /// </summary>
        public static string rdbTeam {
            get {
                return ResourceManager.GetString("rdbTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A problem has ocurred.
        /// </summary>
        public static string SentEmailIssue {
            get {
                return ResourceManager.GetString("SentEmailIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a problem .
        /// </summary>
        public static string ServerErrorMessage {
            get {
                return ResourceManager.GetString("ServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello! I invite you to join my game. The code is:.
        /// </summary>
        public static string tbxBodyInvitation {
            get {
                return ResourceManager.GetString("tbxBodyInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation sent.
        /// </summary>
        public static string tbxEmailSend {
            get {
                return ResourceManager.GetString("tbxEmailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to sign out of Jeopardy?.
        /// </summary>
        public static string tbxSignOut {
            get {
                return ResourceManager.GetString("tbxSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to cancel the game?.
        /// </summary>
        public static string tbxSignOutGame {
            get {
                return ResourceManager.GetString("tbxSignOutGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a s.
        /// </summary>
        public static string ThereIsAnActiveSession {
            get {
                return ResourceManager.GetString("ThereIsAnActiveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A code was sent ....
        /// </summary>
        public static string txbCodeInstructions {
            get {
                return ResourceManager.GetString("txbCodeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A problem has ocurred while saving the user, try again..
        /// </summary>
        public static string txbErrorMessageRegisterUser {
            get {
                return ResourceManager.GetString("txbErrorMessageRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ERROR.
        /// </summary>
        public static string txbErrorTitle {
            get {
                return ResourceManager.GetString("txbErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ban notification.
        /// </summary>
        public static string txbInfoBanner {
            get {
                return ResourceManager.GetString("txbInfoBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The game code has been shared correctly.
        /// </summary>
        public static string txbInfoEmailSend {
            get {
                return ResourceManager.GetString("txbInfoEmailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user has been saved succesfully.
        /// </summary>
        public static string txbInfoMessgSuccRegUser {
            get {
                return ResourceManager.GetString("txbInfoMessgSuccRegUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user has been banned.
        /// </summary>
        public static string txbInformationMessage {
            get {
                return ResourceManager.GetString("txbInformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INFORMATION.
        /// </summary>
        public static string txbInformationTitle {
            get {
                return ResourceManager.GetString("txbInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a last round.
        /// </summary>
        public static string txbLastRoundInstruction {
            get {
                return ResourceManager.GetString("txbLastRoundInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string txbPromtTextSerarch {
            get {
                return ResourceManager.GetString("txbPromtTextSerarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation to the game.
        /// </summary>
        public static string txbTitleEmailInvitation {
            get {
                return ResourceManager.GetString("txbTitleEmailInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are your sure, do want to cancell the process?.
        /// </summary>
        public static string txbWarningMessCloseWin {
            get {
                return ResourceManager.GetString("txbWarningMessCloseWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WARNING.
        /// </summary>
        public static string txbWarningTitle {
            get {
                return ResourceManager.GetString("txbWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a changes saved.
        /// </summary>
        public static string UserChangesSaved {
            get {
                return ResourceManager.GetString("UserChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code is wrong.
        /// </summary>
        public static string WrongCode {
            get {
                return ResourceManager.GetString("WrongCode", resourceCulture);
            }
        }
    }
}
